✨ Add seeding for Users.
ungdev/etu-utt-api pull request #4
Opened 2023-04-24 21:14 UTC by Emalios

Yop l'équipe de beau gosse, voici une pitite PR pour la base du seeding.
Pour ça, Je me suis servie de [Faker](https://fakerjs.dev/guide/) pour les fausses données.

 ## Comment ça fonctionne ?

Y'a un fichier, prisma/seed.ts qui contient un main en typescript qui insére les données dans la db. Ce script est appelé quand on fait la commande "npx prisma db seed" (définie dans le package.json) (selon la doc de prisma c'est aussi appelé automatiquement à d'autre moments, mais je connais pas très bien).

Je pense que c'est mieux de pas mettre la commande dans le docker-compose-dev puisqu'à chaque fois ça signifie devoir rajouter du seed à chaque up de la plateforme (j'ai pas trouvé un moyen de reset proprement, si vous connaissez je pense ça peut être bien d'à chaque fois clean et seed ou bien on le fait à la mano).

Du coup pour seed à la mano, il faut faire un petit 
`docker exec -it etuutt-api sh`
Puis enchaîner avec la fameuse commande:
`npx prisma db seed` 

## La suite ?
Je profite de la PR pour vous demander votre avis sur comment ajouter tous les autres modèles selon vous, est-ce qu'on continue comme ce que j'ai fais pour les fake users et on fait des boucles pour chaque modèle ou bien vous voyez une meilleure manière de faire ?

2023-04-25 09:24 UTC, ThomasRitaine requested changes
Salut !
Super PR, très bien expliquée.


Avant de la merger, j'ai quelques remarques :
- Quand on va avoir des dizaine de fichier de seeding, ils vont tous polluer le dossier `prisma`, il faudrait donc tous les mettre dans un dossier `/prisma/seeds` par exemple. Et avoir un fichier `index.ts` dans ce dossier qui exporte toutes les fonctions contenues dans ce dossier. Tu peux voir un exemple de ça dans ma PR. C'est un patron de conception utilisé en JS.
- Nommer chaque fonction et chaque fichier de seed qu'on utilise dans le `seed.ts` selon une convention qu'il faut définir et documenter. (Un fichier par module à seeder par exmple)
- Update le `README.md` avec les cas d'utilisation du seed ainsi que la commande à exécuter.
 
Mais sinon super taf 😉

2023-04-25 11:26 UTC, Emalios commented
> Salut ! Super PR, très bien expliquée.
> 
> Avant de la merger, j'ai quelques remarques :
> 
> * Quand on va avoir des dizaine de fichier de seeding, ils vont tous polluer le dossier `prisma`, il faudrait donc tous les mettre dans un dossier `/prisma/seeds` par exemple. Et avoir un fichier `index.ts` dans ce dossier qui exporte toutes les fonctions contenues dans ce dossier. Tu peux voir un exemple de ça dans ma PR. C'est un patron de conception utilisé en JS.
> * Nommer chaque fonction et chaque fichier de seed qu'on utilise dans le `seed.ts` selon une convention qu'il faut définir et documenter. (Un fichier par module à seeder par exmple)
> * Update le `README.md` avec les cas d'utilisation du seed ainsi que la commande à exécuter.
> 
> Mais sinon super taf 😉

- Par les "différents fichiers de seeds" dont tu parles, tu veux dire les fichiers où on fake les models ? Parce que sinon je comprends pas ta vision de plusieurs fichiers pour seeds. 

- Tu voudrais faire une fonction par fichier et le nommer en fonction du nom du modèle ?

2023-04-28 05:05 UTC, ThomasRitaine commented
>     Par les "différents fichiers de seeds" dont tu parles, tu veux dire les fichiers où on fake les models ? Parce que sinon je comprends pas ta vision de plusieurs fichiers pour seeds.
Oui, quand l'app va grandir en complexité, on va avoir des dizaines de fichier de seeding. Il faut donc les placer dans un sous dossier de prisma. On peut faire un fichier de fake model par module. Un module peut contenir plusieurs models à fake.

Exemple : le module UE va contenir un modèle UE, un modèle de cours, un modèle de credits ECTS, ainsi de suite.

De plus, dans chaque fichier de seeding, il y aura aussi une certaine logique pour que la donnée générée ne soit pas en contradiction avec elle même. Cette logique sera une fonction dans le fichier de seeding qui sera appelé par `prisma/seed.ts`

Exemple : un étudiant ne peut pas suivre 2 fois la même UE le même semestre, ou un étudiant de TC ne peut pas suivre de matière de filière. Ce sont des exemples de couches de logique qu'il n'est pas possible de simuler avec des fakers de données classique.

>     * Tu voudrais faire une fonction par fichier et le nommer en fonction du nom du modèle ?
L'idée serait d'avoir un fichier de seeding par module, voire le découper en plusieurs si le module est très gros. Et à l'intérieur de chaque fichier de seeding il y aurait des faker de modèle, et des faker pour les logiques comme l'exemple au-dessus.
Le fichier `seed.ts` appelle les différentes fonctions qui se trouvent dans les différents fichiers de seeding.

2023-04-28 12:15 UTC, Emalios commented
> > ```
> > Par les "différents fichiers de seeds" dont tu parles, tu veux dire les fichiers où on fake les models ? Parce que sinon je comprends pas ta vision de plusieurs fichiers pour seeds.
> > ```
> 
> Oui, quand l'app va grandir en complexité, on va avoir des dizaines de fichier de seeding. Il faut donc les placer dans un sous dossier de prisma. On peut faire un fichier de fake model par module. Un module peut contenir plusieurs models à fake.
> 
> Exemple : le module UE va contenir un modèle UE, un modèle de cours, un modèle de credits ECTS, ainsi de suite.
> 
> De plus, dans chaque fichier de seeding, il y aura aussi une certaine logique pour que la donnée générée ne soit pas en contradiction avec elle même. Cette logique sera une fonction dans le fichier de seeding qui sera appelé par `prisma/seed.ts`
> 
> Exemple : un étudiant ne peut pas suivre 2 fois la même UE le même semestre, ou un étudiant de TC ne peut pas suivre de matière de filière. Ce sont des exemples de couches de logique qu'il n'est pas possible de simuler avec des fakers de données classique.
> 
> > ```
> > * Tu voudrais faire une fonction par fichier et le nommer en fonction du nom du modèle ?
> > ```
> 
> L'idée serait d'avoir un fichier de seeding par module, voire le découper en plusieurs si le module est très gros. Et à l'intérieur de chaque fichier de seeding il y aurait des faker de modèle, et des faker pour les logiques comme l'exemple au-dessus. Le fichier `seed.ts` appelle les différentes fonctions qui se trouvent dans les différents fichiers de seeding.

Okep, j'ai fais les modifs, si j'ai bien tout compris tu veux que ça ressemble à quelque chose du genre. T'as le nom du design pattern avec le index qui export tout ? Puisque je comprends pas trop comme les fichiers en eux mêmes exportent déjà leurs fonctions/classes.

2023-05-01 03:07 UTC, ThomasRitaine commented
## Folder structure

Je pense qu'on va se perdre si le dossier qui contient les seeds de tous les modules s'appelle `prisma/module`.
Que penses-tu de faire un dossier `prisma/seed` où on y met le `seed.ts` ainsi que le dossier `module` que tu as créé ? De cette façon on sépare bien les composants nécessaires à Prisma des composants optionnels comme le seeding.

## Utilisation des Enum

Dans ta génération d'UE, tu utilises une liste de code : `const codes = ["EG", "IF", "LO", "LE", "MT", "HT", "MA"]`
Je te conseille de générer les codes aléatoirement, pas besoin qu'ils matchent le réel. L'association aux catégorie CS, TM, etc se fera via des relations Prisma.
Et quand tu as besoin de données avérées comme les code des branches dans cet exemple, je te conseille d'utiliser les Enums qui seront faites quand le module des branches sera développé. `filiereId: faker.helpers.arrayElement(["ISI", "GM", "RT", "MTE"])`

## Prisma Client

Enfin, est-ce que tu peux utiliser `PrismaService` au lieu de prisma client ? C'est un override qu'on fait du prisma client propre à notre application qui permet de modifier la config du prisma client partout dans notre app en modifiant un seul endroit.
Je te laisse regarder dans le module d'auth

2023-05-01 11:47 UTC, Emalios commented
> ## Folder structure
> Je pense qu'on va se perdre si le dossier qui contient les seeds de tous les modules s'appelle `prisma/module`. Que penses-tu de faire un dossier `prisma/seed` où on y met le `seed.ts` ainsi que le dossier `module` que tu as créé ? De cette façon on sépare bien les composants nécessaires à Prisma des composants optionnels comme le seeding.
> 
> ## Utilisation des Enum
> Dans ta génération d'UE, tu utilises une liste de code : `const codes = ["EG", "IF", "LO", "LE", "MT", "HT", "MA"]` Je te conseille de générer les codes aléatoirement, pas besoin qu'ils matchent le réel. L'association aux catégorie CS, TM, etc se fera via des relations Prisma. Et quand tu as besoin de données avérées comme les code des branches dans cet exemple, je te conseille d'utiliser les Enums qui seront faites quand le module des branches sera développé. `filiereId: faker.helpers.arrayElement(["ISI", "GM", "RT", "MTE"])`
> 
> ## Prisma Client
> Enfin, est-ce que tu peux utiliser `PrismaService` au lieu de prisma client ? C'est un override qu'on fait du prisma client propre à notre application qui permet de modifier la config du prisma client partout dans notre app en modifiant un seul endroit. Je te laisse regarder dans le module d'auth

## Folder Structure

C'est changé, en effet je pense c'est mieux comme ça t'as raison.

## Utilisation des enums

Pour les codes c'est plus que je voyais pas trop comment les générés random, prendre deux lttres au pif de l'alphabet ? J'ai pensé que quitte à faire ça autant choisir un elem random parmis ma liste. 

## PrismaClient

Alors là du coup c'est plus compliqué, le problème c'est que PrismaService bah c'est un service nestJs, tu peux pas l'utiliser dans un fichier random ts comme notre seed.ts, fin en tout cas j'ai rien trouvé, cependant un truc possible c'est de faire en sorte que le seed.ts, soit une application nestJS et qu'il ait aussi par conséquent des modules qu'il puisse utiliser, on peut très bien imaginer avoir du coup le PrismaService et ensuite un Service par module à seed, j'ai trouvé l'idée [ici](https://dev.to/elpddev/nest-ioc-di-dependency-injection-as-a-seeds-tasks-runner-57k2), mais ça me semble un peu usine à gaz pour ce qu'on veut, qu'est-ce que tu voulais faire de plus avec le PrismaService par rapport au PrismaClient ?

2023-05-01 21:34 UTC, ThomasRitaine commented
## Folder Structure
> C'est changé, en effet je pense c'est mieux comme ça t'as raison.

Ok parfait ! Tu peux commit et on est bon

## Utilisation des enums
> Pour les codes c'est plus que je voyais pas trop comment les générés random, prendre deux lttres au pif de l'alphabet ? J'ai pensé que quitte à faire ça autant choisir un elem random parmis ma liste.

Ok, je suis d'accord avec toi. Mais pour les branches qui ont des codes bien particuliers, il faudra les récupérer dans le `schema.prisma` par le client prisma quand le module sera développé. En attendant tu peux mettre un commentaire en anglais au dessus. (En anglais pour uniformiser la codebase)

## PrismaClient
> Alors là du coup c'est plus compliqué, le problème c'est que PrismaService bah c'est un service nestJs, tu peux pas l'utiliser dans un fichier random ts comme notre seed.ts, fin en tout cas j'ai rien trouvé, cependant un truc possible c'est de faire en sorte que le seed.ts, soit une application nestJS et qu'il ait aussi par conséquent des modules qu'il puisse utiliser, on peut très bien imaginer avoir du coup le PrismaService et ensuite un Service par module à seed, j'ai trouvé l'idée [ici](https://dev.to/elpddev/nest-ioc-di-dependency-injection-as-a-seeds-tasks-runner-57k2), mais ça me semble un peu usine à gaz pour ce qu'on veut, qu'est-ce que tu voulais faire de plus avec le PrismaService par rapport au PrismaClient ?

Ok, merci pour la doc et l'explication. En effet, c'est galère et je pense que c'est overkill pour notre projet. On peut rester sur le client Prisma 😁

2023-05-01 21:41 UTC, ThomasRitaine commented on prisma/modules/ue/models/ue.ts
> +//Je mets le code en paramètre puisque pour moi c'est à la logique du seeder de le générer
Yooooo, deux petits points :
1. Est-ce que tu peux mettre tes commentaires en anglais pour uniformiser la codebase ? 😁
2. Au final, tu n'as pas mis le code en paramètre, et je pense que c'est mieux comme ça, la fonction `fakeUE()` s'occupe de tout !

2023-05-01 22:06 UTC, ThomasRitaine requested changes
Ok, je viens de passer en revu la PR. On est presque bon 😉
J'ai mis des commentaires et suggestions.

Aussi, que penses-tu de renommer le dossier `prisma/modules/ue/models` en `prisma/modules/ue/factories` ? De même pour le module user et les autres qui suivront.
C'est parce que le terme `models` est en général utilisé pour définir de nouveaux objets. Là, on utilise les objets déjà existant où en crée des instances avec des données fake. Le terme `factories` est assez commun en seeding, et il reprend plutôt bien l'idée. Qu'est-ce que tu en penses ?

Je suis désolé, je t'embête un peu, mais une fois qu'on a des bases solides sur le projet, ca va développer sec 😏

2023-05-01 22:45 UTC, Emalios commented
> Ok, je viens de passer en revu la PR. On est presque bon 😉 J'ai mis des commentaires et suggestions.
> 
> Aussi, que penses-tu de renommer le dossier `prisma/modules/ue/models` en `prisma/modules/ue/factories` ? De même pour le module user et les autres qui suivront. C'est parce que le terme `models` est en général utilisé pour définir de nouveaux objets. Là, on utilise les objets déjà existant où en crée des instances avec des données fake. Le terme `factories` est assez commun en seeding, et il reprend plutôt bien l'idée. Qu'est-ce que tu en penses ?
> 
> Je suis désolé, je t'embête un peu, mais une fois qu'on a des bases solides sur le projet, ca va développer sec 😏

Je regarde ça, je finissais juste de faire fonctionner le seed des ue, c'est un peu la galère parce que y'a des clés étrangères donc faut faire uttbranches, uttfilieres et les translation, après si tu préfères on peut parler sur discord je serais plus réactif et au pire on mettre en com un récap ?

2023-05-01 22:51 UTC, Emalios commented on prisma/modules/ue/models/index.ts
> +export * from './ue'
Aucun soucis, c'est pour éviter les soucis d'encodage ou juste une pratique de js ?

2023-05-01 22:51 UTC, Emalios commented on prisma/modules/ue/models/ue.ts
> +//Je mets le code en paramètre puisque pour moi c'est à la logique du seeder de le générer
C'est outdated car j'ai push un truc avant mais c'est changé !

2023-05-01 22:51 UTC, Emalios commented on prisma/seed.ts
> +    }
C'est changé !

2023-05-01 22:53 UTC, ThomasRitaine commented on prisma/modules/ue/models/index.ts
> +export * from './ue'
C'est une pratique dans presque l'ensemble des lagunages de prog maitenant

2023-05-01 22:54 UTC, Emalios commented
> > Ok, je viens de passer en revu la PR. On est presque bon 😉 J'ai mis des commentaires et suggestions.
> > Aussi, que penses-tu de renommer le dossier `prisma/modules/ue/models` en `prisma/modules/ue/factories` ? De même pour le module user et les autres qui suivront. C'est parce que le terme `models` est en général utilisé pour définir de nouveaux objets. Là, on utilise les objets déjà existant où en crée des instances avec des données fake. Le terme `factories` est assez commun en seeding, et il reprend plutôt bien l'idée. Qu'est-ce que tu en penses ?
> > Je suis désolé, je t'embête un peu, mais une fois qu'on a des bases solides sur le projet, ca va développer sec 😏
> 
> Je regarde ça, je finissais juste de faire fonctionner le seed des ue, c'est un peu la galère parce que y'a des clés étrangères donc faut faire uttbranches, uttfilieres et les translation, après si tu préfères on peut parler sur discord je serais plus réactif et au pire on mettre en com un récap ?

Perso si je devais changer le nom je dirais plutôt Mock nan t'en penses quoi ? Sinon je m'en fiche de mettr factories c'est juste que j'ai pensé à Mock comme on fake les données.

2023-05-01 23:04 UTC, ThomasRitaine commented
> Perso si je devais changer le nom je dirais plutôt Mock nan t'en penses quoi ? Sinon je m'en fiche de mettr factories c'est juste que j'ai pensé à Mock comme on fake les données.

Mock est plutôt utilisé lorsqu'on simule un objet réel, par exemple un network, une application... Là, c'est autre chose, on crée des objets réels en base de données

2023-05-01 23:06 UTC, Emalios commented
> > Perso si je devais changer le nom je dirais plutôt Mock nan t'en penses quoi ? Sinon je m'en fiche de mettr factories c'est juste que j'ai pensé à Mock comme on fake les données.
> 
> Mock est plutôt utilisé lorsqu'on simule un objet réel, par exemple un network, une application... Là, c'est autre chose, on crée des objets réels en base de données

Tu m'as convaincu é_è

2023-12-18 03:02 UTC, TeddyRoncin approved these changes

2023-12-18 03:04 UTC, merged